### ISSUE TITLE
Funcionalidade de criar figura

### ISSUE THREAD

**Issue by marinadore** [rsoutelino/uerj_ocn_2015#4]

**Comment by rsoutelino** [comment]
Ok, boa ideia, vou criar.

**Comment by rsoutelino** [comment]
@marinadore , ja criei a funcao, e deixei como uma funcionalidade opcional. Veja abaixo:

https://github.com/rsoutelino/uerj_ocn_2015/commit/2cdc6cdac3eee89bad393dd7fb2bd94d486b5037
